project:
  type: website
  
website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - Talks.qmd

editor: source

execute:
  echo: true
  
highlight-style: atom-one

# atom-one
# github
# solarized
